-- ============================================================
-- Carbiran Backend Autonome — Schéma PostgreSQL sans Supabase
-- Remplace auth.users + public.profiles de Supabase
-- Exécuter une seule fois : psql $DATABASE_URL -f migration.sql
-- ============================================================

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ============================================================
-- Trigger updated_at (partagé par toutes les tables)
-- ============================================================

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

-- ============================================================
-- 1. Table users (remplace auth.users + public.profiles)
-- ============================================================

CREATE TABLE IF NOT EXISTS public.users (
  id                 uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  email              text        UNIQUE NOT NULL,
  password_hash      text        NOT NULL,
  nom                text,
  prenom             text,
  role               text        NOT NULL DEFAULT 'viewer'
                                 CHECK (role IN (
                                   'Admin', 'MENAGER', 'viewer',
                                   'chef_de_cours', 'chef_departement',
                                   'responsable_station', 'responsable_station_viewer',
                                   'signataire'
                                 )),
  departement        text,
  circuit_role       text,
  notification_email text,
  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_users_email ON public.users(email);
CREATE INDEX IF NOT EXISTS idx_users_role  ON public.users(role);

CREATE OR REPLACE TRIGGER trg_users_updated_at
  BEFORE UPDATE ON public.users
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ============================================================
-- 2. Véhicules
-- ============================================================

CREATE TABLE IF NOT EXISTS public.vehicules (
  id                      bigint  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vehicule                text    NOT NULL CHECK (trim(vehicule) <> ''),
  matricule               text    NOT NULL UNIQUE CHECK (trim(matricule) <> ''),
  utilisation_affectation text    NOT NULL CHECK (trim(utilisation_affectation) <> ''),
  chauffeur_responsable   text,
  zone                    text    NOT NULL CHECK (trim(zone) <> ''),
  centre                  text,
  created_at              timestamptz NOT NULL DEFAULT now(),
  updated_at              timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_vehicules_zone      ON public.vehicules(zone);
CREATE INDEX IF NOT EXISTS idx_vehicules_matricule ON public.vehicules(matricule);

CREATE OR REPLACE TRIGGER trg_vehicules_updated_at
  BEFORE UPDATE ON public.vehicules
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ============================================================
-- 3. Ravitaillements véhicules (journal carburant direct)
-- ============================================================

CREATE TABLE IF NOT EXISTS public.ravitaillements_vehicules (
  id                bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date              date         NOT NULL,
  vehicule_id       bigint       NOT NULL REFERENCES public.vehicules(id) ON DELETE RESTRICT,
  montant_ravitaille numeric(14,2) NOT NULL CHECK (montant_ravitaille >= 0),
  commentaire       text         NOT NULL DEFAULT '',
  kilometrage       numeric(14,2) NOT NULL DEFAULT 0 CHECK (kilometrage >= 0),
  n_liter           numeric(14,2) NOT NULL DEFAULT 0 CHECK (n_liter >= 0),
  created_at        timestamptz  NOT NULL DEFAULT now(),
  updated_at        timestamptz  NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_rav_vehicule_id ON public.ravitaillements_vehicules(vehicule_id);
CREATE INDEX IF NOT EXISTS idx_rav_date        ON public.ravitaillements_vehicules(date);

CREATE OR REPLACE TRIGGER trg_rav_updated_at
  BEFORE UPDATE ON public.ravitaillements_vehicules
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ============================================================
-- 4. Demandes de ravitaillement
-- ============================================================

CREATE TABLE IF NOT EXISTS public.demandes_ravitaillement (
  id               uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  departement      text        NOT NULL
                               CHECK (departement IN ('Zone A','Zone B','RS','RX&SYS','FO','CPDE','DC','Autre')),
  statut           text        NOT NULL DEFAULT 'en_attente'
                               CHECK (statut IN ('en_attente','validee_dept','validee_station','validee_cellule','annulee')),
  situation_soumise boolean    NOT NULL DEFAULT false,
  created_by       uuid        NOT NULL REFERENCES public.users(id) ON DELETE RESTRICT,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_demandes_created_by  ON public.demandes_ravitaillement(created_by);
CREATE INDEX IF NOT EXISTS idx_demandes_departement ON public.demandes_ravitaillement(departement);
CREATE INDEX IF NOT EXISTS idx_demandes_statut      ON public.demandes_ravitaillement(statut);

CREATE OR REPLACE TRIGGER trg_demandes_updated_at
  BEFORE UPDATE ON public.demandes_ravitaillement
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ============================================================
-- 5. Véhicules d'une demande
-- ============================================================

CREATE TABLE IF NOT EXISTS public.demande_vehicules (
  id          uuid         PRIMARY KEY DEFAULT gen_random_uuid(),
  demande_id  uuid         NOT NULL REFERENCES public.demandes_ravitaillement(id) ON DELETE CASCADE,
  vehicule_id bigint       NOT NULL REFERENCES public.vehicules(id) ON DELETE RESTRICT,
  montant     numeric(14,2),
  n_liter     numeric(14,2),
  kilometrage numeric(14,2),
  statut      text         NOT NULL DEFAULT 'en_attente'
                           CHECK (statut IN ('en_attente','ravitaille','valide','refuse')),
  created_at  timestamptz  NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_dv_demande_id  ON public.demande_vehicules(demande_id);
CREATE INDEX IF NOT EXISTS idx_dv_vehicule_id ON public.demande_vehicules(vehicule_id);

-- ============================================================
-- 6. Photos justification
-- ============================================================

CREATE TABLE IF NOT EXISTS public.photos_justification (
  id                  uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  demande_vehicule_id uuid        NOT NULL REFERENCES public.demande_vehicules(id) ON DELETE CASCADE,
  url                 text        NOT NULL,
  type                text        NOT NULL
                                  CHECK (type IN ('vehicule_avant','vehicule_apres','pompe')),
  uploaded_at         timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_photos_dv_id ON public.photos_justification(demande_vehicule_id);

-- ============================================================
-- 7. Notifications
-- ============================================================

CREATE TABLE IF NOT EXISTS public.notifications (
  id         uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id    uuid        NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  message    text        NOT NULL,
  type       text        NOT NULL,
  lu         boolean     NOT NULL DEFAULT false,
  demande_id uuid        REFERENCES public.demandes_ravitaillement(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_notif_user_id    ON public.notifications(user_id);
CREATE INDEX IF NOT EXISTS idx_notif_demande_id ON public.notifications(demande_id);

-- ============================================================
-- 8. Signatures enregistrées par utilisateur
-- ============================================================

CREATE TABLE IF NOT EXISTS public.signatures_utilisateurs (
  id            uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id       uuid        NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  role          text        NOT NULL,
  signature_url text        NOT NULL,
  created_at    timestamptz DEFAULT now(),
  CONSTRAINT signatures_utilisateurs_user_id_unique UNIQUE (user_id)
);

-- ============================================================
-- 9. Signatures apposées sur une demande
-- ============================================================

CREATE TABLE IF NOT EXISTS public.signatures_situation (
  id            uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  demande_id    uuid        REFERENCES public.demandes_ravitaillement(id) ON DELETE CASCADE,
  role          text        NOT NULL,
  user_id       uuid        REFERENCES public.users(id) ON DELETE SET NULL,
  signature_url text,
  signe_le      timestamptz DEFAULT now(),
  ordre         integer     NOT NULL,
  circuit       text        NOT NULL DEFAULT 'situation',
  CONSTRAINT signatures_situation_demande_role_circuit_unique UNIQUE (demande_id, role, circuit)
);

CREATE INDEX IF NOT EXISTS idx_sigs_demande_id ON public.signatures_situation(demande_id);

-- ============================================================
-- 10. Journal d'activité
-- ============================================================

CREATE TABLE IF NOT EXISTS public.activity_logs (
  id           bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at   timestamptz NOT NULL DEFAULT now(),
  user_id      uuid        REFERENCES public.users(id) ON DELETE SET NULL,
  user_email   text,
  module       text        NOT NULL,
  action       text        NOT NULL,
  target_table text,
  target_id    text,
  description  text,
  before_data  jsonb,
  after_data   jsonb,
  metadata     jsonb
);

CREATE INDEX IF NOT EXISTS idx_activity_created_at ON public.activity_logs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_activity_module     ON public.activity_logs(module);
CREATE INDEX IF NOT EXISTS idx_activity_user_id    ON public.activity_logs(user_id);

-- ============================================================
-- Utilisateur Admin initial
-- Générez le hash avec :
--   node -e "const b=require('bcryptjs'); console.log(b.hashSync('changeme!',10))"
-- puis remplacez HASH_ICI ci-dessous
-- ============================================================

-- INSERT INTO public.users (email, password_hash, nom, prenom, role)
-- VALUES ('admin@carbiran.mr', 'HASH_ICI', 'Admin', 'Système', 'Admin')
-- ON CONFLICT (email) DO NOTHING;
