begin;

create table if not exists public.activity_logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id uuid references public.profiles(id) on delete set null,
  user_email text,
  module text not null,
  action text not null,
  target_table text,
  target_id text,
  description text,
  before_data jsonb,
  after_data jsonb,
  metadata jsonb
);

create index if not exists idx_activity_logs_created_at on public.activity_logs(created_at desc);
create index if not exists idx_activity_logs_module on public.activity_logs(module);
create index if not exists idx_activity_logs_user_id on public.activity_logs(user_id);
create index if not exists idx_activity_logs_target on public.activity_logs(target_table, target_id);

grant select, insert on public.activity_logs to authenticated;
grant usage, select on sequence public.activity_logs_id_seq to authenticated;

alter table public.activity_logs enable row level security;

drop policy if exists "activity_logs_admin_select" on public.activity_logs;
create policy "activity_logs_admin_select"
on public.activity_logs
for select
to authenticated
using (public.is_admin());

drop policy if exists "activity_logs_insert_own" on public.activity_logs;
create policy "activity_logs_insert_own"
on public.activity_logs
for insert
to authenticated
with check (auth.uid() = user_id);

commit;
