insert into public.vehicules (
  vehicule,
  matricule,
  utilisation_affectation,
  chauffeur_responsable,
  zone
)
values
  ('Verso', '8517BB00', 'Instalation BLR', 'Chekh Abeidi', 'Zone A'),
  ('Bus', '7545AX00', 'Projet', 'Sidi Mohamed Elewa', 'FO'),
  ('Hilux', '6469AY00', 'Raid', 'El Hacen Barek/sidimhamed', 'Zone A'),
  ('Hilux', '5020BC00', 'Projet', 'Elken', 'RX&SYS'),
  ('Kango', '2871BA00', 'Instalation FTTH', 'Bouh Kheri', 'Zone A'),
  ('Kango', '5026AZ00', 'Instalation FTTH', 'Med Yenge Abeld', 'Zone A'),
  ('Kango', '3668BA00', 'Derangement FTTH', 'El Bekaye Saleck', 'Zone A'),
  ('Kango', '4690AZ00', 'Derangement FTTH', 'Abdelahi Deye', 'Zone A'),
  ('Grue', '6782BB0', 'Projet', 'Alioune', 'FO'),
  ('L200', '0645AA05', 'Deploiement FTTH et LS', 'Sidahmed', 'Zone A'),
  ('Kango', '4868AZ00', 'Derangement FTTH', 'Abderrahman ebouh', 'FO'),
  ('Kango', '4323BA00', 'BLR', 'Moulay', 'Zone A'),
  ('Kango', '4083AX00', 'Raccordement', 'Sidimhamed', 'FO'),
  ('BUS', '5898BA00', 'Projet', 'El Houssein', 'FO'),
  ('Kango', '5928AZ00', 'Derangement BLR', 'Ahmed salem', 'Zone A'),
  ('Kango', '2354AX00', 'Derangement FTTH', 'Ahmed', 'Zone A'),
  ('Kango', '7017AY00', 'Derangement SAWI', 'Gali', 'Zone A'),
  ('Kango', '4149AY00', 'Derangement SAWI', 'Med Lemin', 'Zone A'),
  ('Kango', '3456BA00', 'Instalation SAWI', 'El Kouri Tibe', 'Zone A'),
  ('Kango', '6581AY00', 'Instalation SAWI', 'Brahim Ahmedou Salem', 'Zone A'),
  ('Kango', '4869AZ00', 'Derangement SAWI', 'Med Ahmed Eli', 'Zone A'),
  ('Kango', '5043AZ00', 'Instalation SAWI', 'Chekhna', 'Zone A'),
  ('Verso', '1007AC00', 'Maintenance', 'Med Vadel', 'Zone A'),
  ('Hilux', '0423AZ00', 'Genie Civil', 'Mestapha', 'Zone A'),
  ('Hilux', '2315AZ00', 'Maintenance', 'Ebah', 'Zone A'),
  ('Verso', '2729BA00', 'Maintenance', 'Si El Mekhtar', 'RX&SYS'),
  ('Verso', '0499AZ00', 'Raccordement', 'Babe Med Abdelahi', 'FO'),
  ('Hilux', '5471BA00', 'Chantier', 'Abdou', 'CPDE'),
  ('Hilux', '0963AY00', 'Raccordement', 'Smael', 'FO'),
  ('Hilux', '2556AY00', 'Raccordement', 'Idoumou', 'FO'),
  ('Hilux', '8926AY00', 'Trancheuse', 'Chekh', 'CPDE'),
  ('Hilux', '9592AY00', 'Centure', 'Sidimkhtar', 'CPDE'),
  ('Hilux', '3812BB00', 'Center Technique de Sellibabi', 'Mouhamed Yeslem', 'Zone B'),
  ('Hilux', '2538AZ00', 'Centre Technique de Basseknou', 'Taleb Ahmed', 'Zone B'),
  ('Hilux', '5014BC00', 'Center Technique de Aioun', 'Yeslem issawi', 'Zone B'),
  ('Hilux', '5019BC00', 'Centre Technique de Rosso', 'El Gassem', 'Zone A'),
  ('Hilux', '1883BA00', 'Centre Technique de Alag', 'Brahim', 'Zone B'),
  ('Hilux', '5021BC00', 'Centre Technique de Kaedi', 'Med Valle Dehan', 'Zone B'),
  ('Hilux', '5321AZ00', 'Centre Technique de NEMA', 'Chekhna', 'Zone B'),
  ('Hilux', '1882BA00', 'Centre Technique de KIFFA', 'Med Saed', 'Zone B'),
  ('Kango', '9977AY00', 'NDB', 'En Panne', 'Zone A'),
  ('Kango', '2870BA00', 'NDB', null, 'Zone A'),
  ('Bus', '7535AX00', 'NDB', 'Med Chekh', 'Zone A'),
  ('Hilux', '0424AZ00', 'NDB', 'Hamoud Tahmid', 'Zone A'),
  ('Verso', '8562BB00', 'NDB', 'Dah Hamoud', 'Zone A'),
  ('Verso', '2122BC00', 'NDB', 'Mohamed Salek', 'Zone A'),
  ('Verso', '4795BB00', 'Boulware', 'Moustapha Abdelkader', 'Zone A'),
  ('Hilux', '1881BA00', 'Centre Technique de ZWEIRATE', 'Yahve', 'Zone A'),
  ('Bus', '7696BB00', 'Centre Technique de ZWEIRATE', 'Mouhamed elmami', 'Zone A'),
  ('Kango', '0089AY00', 'ROSSO', 'Sidi', 'Zone A'),
  ('aaa', '6557BB00', 'ATAR', 'Sidi ahmed', 'Zone A'),
  ('bbbbb', '5889AM00', 'Projet RIAD', 'Projet RIAD', 'Zone A'),
  ('cccccc', '2942AC07', 'Projet RIAD', 'Projet RIAD', 'Zone A'),
  ('dddd', '4862BB00', 'NO identifier', 'NO identifier', 'Zone A'),
  ('Grue', '2152AY00', 'FIBRE', 'NO identifier', 'FO'),
  ('Hilux', '6746AA06', 'NO identifier', 'NO identifier', 'FO'),
  ('ffff', '6199AA03', 'NO identifier', 'NO identifier', 'Zone A'),
  ('ffff', '9124AP00', 'NO identifier', 'NO identifier', 'Zone A'),
  ('ffff', '5989AM', 'NO identifier', 'NO identifier', 'Zone A'),
  ('MOTO', 'MOTO1', 'MBRRE', 'MBRRE', 'Zone B'),
  ('ggg', '8462BB', 'fibre ndb', 'Sidaty', 'Zone A'),
  ('GGG', 'ANTENNE', 'NDB', 'Sidaty', 'Zone A'),
  ('Hilux', '3636AA07', 'FIBRE', null, 'FO'),
  ('Hilux', '1615AV00', 'Zone A', 'zone a', 'Zone A'),
  ('gazoil', '8650AA07', 'ZONE A', 'SIDI MED ALEWA', 'ZONE A'),
  ('gazoil', '5523AB07', 'Zone A', 'LEMANE', 'Zone A'),
  ('groupe creusage', 'groupe creusage', 'Zone A', 'Sidaty', 'Zone A'),
  ('groupe ndb1', 'groupe ndb1', 'ZONe A', 'Sidaty', 'Zone A'),
  ('voiture essence', '1406AC06', 'Direction commerciale', 'Direction commerciale', 'Direction commerciale'),
  ('moto basseknou', 'moto basseknou', 'zone B', null, 'zone B'),
  ('groupe siege', 'groupe siege', 'Zone A', null, 'ZONE A'),
  ('groupe du travail', 'groupe du travail', 'Zone A', null, 'Zone A'),
  ('groupe aioune', 'groupe aioune', 'Zone B', null, 'Zone B'),
  ('groupe kaedi', 'groupe kaedi', 'Zone B', null, 'Zone B')
on conflict (matricule) do nothing;
