-- Schema Supabase / Postgres - version finale
-- Date de reference: 2026-05-06

begin;

-- =========================================================
-- 1. Types enum
-- =========================================================

do $$
begin
  if not exists (
    select 1
    from pg_type
    where typname = 'app_role'
  ) then
    create type public.app_role as enum ('Admin', 'MENAGER', 'viewer');
  end if;
end $$;

-- =========================================================
-- 2. Fonction utilitaire
-- =========================================================

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- =========================================================
-- 3. Profiles
-- =========================================================

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text unique,
  nom text,
  prenom text,
  role public.app_role not null default 'viewer',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists trg_profiles_updated_at on public.profiles;
create trigger trg_profiles_updated_at
before update on public.profiles
for each row
execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, nom, prenom, role)
  values (
    new.id,
    new.email,
    new.raw_user_meta_data ->> 'nom',
    new.raw_user_meta_data ->> 'prenom',
    coalesce((new.raw_user_meta_data ->> 'role')::public.app_role, 'viewer')
  )
  on conflict (id) do update
  set
    email = excluded.email,
    nom = coalesce(public.profiles.nom, excluded.nom),
    prenom = coalesce(public.profiles.prenom, excluded.prenom),
    role = coalesce(public.profiles.role, excluded.role);

  return new;
exception
  when others then
    return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row
execute function public.handle_new_user();

insert into public.profiles (id, email, nom, prenom, role)
select
  u.id,
  u.email,
  u.raw_user_meta_data ->> 'nom',
  u.raw_user_meta_data ->> 'prenom',
  coalesce((u.raw_user_meta_data ->> 'role')::public.app_role, 'viewer')
from auth.users u
on conflict (id) do update
set
  email = excluded.email,
  nom = coalesce(public.profiles.nom, excluded.nom),
  prenom = coalesce(public.profiles.prenom, excluded.prenom),
  role = coalesce(public.profiles.role, excluded.role);

-- =========================================================
-- 4. Fonctions RLS
-- =========================================================

create or replace function public.current_app_role()
returns public.app_role
language sql
stable
security definer
set search_path = public
as $$
  select p.role
  from public.profiles p
  where p.id = auth.uid()
  limit 1
$$;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    (
      select p.role = 'Admin'
      from public.profiles p
      where p.id = auth.uid()
      limit 1
    ),
    false
  )
$$;

create or replace function public.is_manager_or_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    (
      select p.role in ('Admin', 'MENAGER')
      from public.profiles p
      where p.id = auth.uid()
      limit 1
    ),
    false
  )
$$;

revoke all on function public.current_app_role() from public;
revoke all on function public.is_admin() from public;
revoke all on function public.is_manager_or_admin() from public;

grant execute on function public.current_app_role() to authenticated;
grant execute on function public.is_admin() to authenticated;
grant execute on function public.is_manager_or_admin() to authenticated;

-- =========================================================
-- 5. Vehicules
-- =========================================================

create table if not exists public.vehicules (
  id bigint generated by default as identity primary key,
  vehicule text not null,
  matricule text not null unique,
  utilisation_affectation text not null,
  chauffeur_responsable text,
  zone text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint vehicules_vehicule_not_blank check (btrim(vehicule) <> ''),
  constraint vehicules_matricule_not_blank check (btrim(matricule) <> ''),
  constraint vehicules_utilisation_not_blank check (btrim(utilisation_affectation) <> ''),
  constraint vehicules_zone_not_blank check (btrim(zone) <> '')
);

drop trigger if exists trg_vehicules_updated_at on public.vehicules;
create trigger trg_vehicules_updated_at
before update on public.vehicules
for each row
execute function public.set_updated_at();

create index if not exists idx_vehicules_zone on public.vehicules(zone);
create index if not exists idx_vehicules_vehicule on public.vehicules(vehicule);
create index if not exists idx_vehicules_matricule on public.vehicules(matricule);

-- =========================================================
-- 6. Ravitaillements vehicules
-- =========================================================

create table if not exists public.ravitaillements_vehicules (
  id bigint generated by default as identity primary key,
  date date not null,
  vehicule_id bigint not null references public.vehicules(id) on delete restrict,
  montant_ravitaille numeric(14,2) not null,
  commentaire text not null default '',
  kilometrage numeric(14,2) not null default 0,
  n_liter numeric(14,2) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint rav_montant_ravitaille_non_negatif check (
    montant_ravitaille >= 0
  ),
  constraint rav_commentaire_not_null check (
    commentaire is not null
  ),
  constraint rav_kilometrage_non_negatif check (
    kilometrage >= 0
  ),
  constraint rav_n_liter_non_negatif check (
    n_liter >= 0
  )
);

drop trigger if exists trg_ravitaillements_vehicules_updated_at on public.ravitaillements_vehicules;
create trigger trg_ravitaillements_vehicules_updated_at
before update on public.ravitaillements_vehicules
for each row
execute function public.set_updated_at();

create index if not exists idx_rav_vehicule_id on public.ravitaillements_vehicules(vehicule_id);
create index if not exists idx_rav_date on public.ravitaillements_vehicules(date);

-- =========================================================
-- 7. Journal d'activite
-- =========================================================

create table if not exists public.activity_logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id uuid references public.profiles(id) on delete set null,
  user_email text,
  module text not null,
  action text not null,
  target_table text,
  target_id text,
  description text,
  before_data jsonb,
  after_data jsonb,
  metadata jsonb
);

create index if not exists idx_activity_logs_created_at on public.activity_logs(created_at desc);
create index if not exists idx_activity_logs_module on public.activity_logs(module);
create index if not exists idx_activity_logs_user_id on public.activity_logs(user_id);
create index if not exists idx_activity_logs_target on public.activity_logs(target_table, target_id);

-- =========================================================
-- 8. Vue de compatibilite
-- =========================================================

drop view if exists public.admins;
create view public.admins as
select
  p.id as user_id
from public.profiles p
where p.role in ('Admin', 'MENAGER');

-- =========================================================
-- 9. Permissions
-- =========================================================

grant usage on schema public to anon, authenticated;
grant select on public.admins to authenticated;

grant select on public.profiles to authenticated;
grant insert, update on public.profiles to authenticated;

grant select on public.vehicules to authenticated;
grant insert, update, delete on public.vehicules to authenticated;

grant select on public.ravitaillements_vehicules to authenticated;
grant insert, update, delete on public.ravitaillements_vehicules to authenticated;

grant select, insert on public.activity_logs to authenticated;

grant usage, select on all sequences in schema public to authenticated;

-- =========================================================
-- 10. RLS
-- =========================================================

alter table public.profiles enable row level security;
alter table public.vehicules enable row level security;
alter table public.ravitaillements_vehicules enable row level security;
alter table public.activity_logs enable row level security;

drop policy if exists "profiles_select_own_or_manager" on public.profiles;
create policy "profiles_select_own_or_manager"
on public.profiles
for select
to authenticated
using (
  id = auth.uid()
  or public.is_manager_or_admin()
);

drop policy if exists "profiles_insert_admin_only" on public.profiles;
create policy "profiles_insert_admin_only"
on public.profiles
for insert
to authenticated
with check (
  public.is_admin()
);

drop policy if exists "profiles_update_self_or_admin" on public.profiles;
create policy "profiles_update_self_or_admin"
on public.profiles
for update
to authenticated
using (
  id = auth.uid()
  or public.is_admin()
)
with check (
  id = auth.uid()
  or public.is_admin()
);

drop policy if exists "profiles_delete_admin_only" on public.profiles;
create policy "profiles_delete_admin_only"
on public.profiles
for delete
to authenticated
using (
  public.is_admin()
);

drop policy if exists "vehicules_select_all_authenticated" on public.vehicules;
create policy "vehicules_select_all_authenticated"
on public.vehicules
for select
to authenticated
using (true);

drop policy if exists "vehicules_write_manager_or_admin" on public.vehicules;
create policy "vehicules_write_manager_or_admin"
on public.vehicules
for all
to authenticated
using (public.is_manager_or_admin())
with check (public.is_manager_or_admin());

drop policy if exists "ravitaillements_select_all_authenticated" on public.ravitaillements_vehicules;
create policy "ravitaillements_select_all_authenticated"
on public.ravitaillements_vehicules
for select
to authenticated
using (true);

drop policy if exists "ravitaillements_write_manager_or_admin" on public.ravitaillements_vehicules;
create policy "ravitaillements_write_manager_or_admin"
on public.ravitaillements_vehicules
for all
to authenticated
using (public.is_manager_or_admin())
with check (public.is_manager_or_admin());

drop policy if exists "activity_logs_admin_select" on public.activity_logs;
create policy "activity_logs_admin_select"
on public.activity_logs
for select
to authenticated
using (public.is_admin());

drop policy if exists "activity_logs_insert_own" on public.activity_logs;
create policy "activity_logs_insert_own"
on public.activity_logs
for insert
to authenticated
with check (auth.uid() = user_id);

commit;
